In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,6])

In [7]:
b = a

In [8]:
a

array([1, 2, 3, 4, 6])

In [9]:
b

array([1, 2, 3, 4, 6])

In [10]:
b[0] = 100

In [11]:
b

array([100,   2,   3,   4,   6])

In [12]:
a

array([100,   2,   3,   4,   6])

In [13]:
a[-1] = 50

In [14]:
a

array([100,   2,   3,   4,  50])

In [15]:
b

array([100,   2,   3,   4,  50])

In [16]:
id(a)

140359576110256

In [17]:
id(b)

140359576110256

In [18]:
b = a.view()

In [19]:
a = np.array([1,2,3,4,5])

In [20]:
b = a.copy()

In [21]:
a

array([1, 2, 3, 4, 5])

In [22]:
b

array([1, 2, 3, 4, 5])

In [23]:
a[0] = 100

In [24]:
a

array([100,   2,   3,   4,   5])

In [25]:
b

array([1, 2, 3, 4, 5])

In [26]:
a = np.arange(25)

In [27]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [28]:
b = np.reshape(a, (5,5))

In [29]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [31]:
c = np.reshape(a, (6,2))

ValueError: cannot reshape array of size 25 into shape (6,2)

In [32]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [34]:
b[0,0] = 101

In [35]:
b

array([[101,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [36]:
a

array([101,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [37]:
a

array([101,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24])

In [38]:
a.reshape((5,5))

array([[101,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14],
       [ 15,  16,  17,  18,  19],
       [ 20,  21,  22,  23,  24]])

In [39]:
np.arange(100).reshape((10,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [41]:
np.arange(25).reshape((5, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [46]:
a = np.arange(25)

In [47]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
a.resize((4,4), refcheck=False)

In [50]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [51]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
b = np.ravel(a)

In [54]:
b[0] = 1000

In [55]:
a

array([[1000,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11],
       [  12,   13,   14,   15]])

In [56]:
b

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15])

In [57]:
a

array([[1000,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11],
       [  12,   13,   14,   15]])

In [58]:
b = a.flatten()

In [59]:
a

array([[1000,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11],
       [  12,   13,   14,   15]])

In [60]:
b

array([1000,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15])

In [61]:
b[0] = 200

In [62]:
b

array([200,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15])

In [63]:
a

array([[1000,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11],
       [  12,   13,   14,   15]])

In [64]:
np.Inf

inf

In [65]:
type(np.Inf)

float

In [66]:
np.sum([1,2,3,4,5,6])

21

In [67]:
np.prod([1,2,3])

6

In [68]:
np.max([1,2,3])

3

In [69]:
a

array([[1000,    1,    2,    3],
       [   4,    5,    6,    7],
       [   8,    9,   10,   11],
       [  12,   13,   14,   15]])

In [70]:
a.T

array([[1000,    4,    8,   12],
       [   1,    5,    9,   13],
       [   2,    6,   10,   14],
       [   3,    7,   11,   15]])

In [71]:
a = np.arange(25)

In [72]:
a.mean()

12.0

In [73]:
np.mean(a)

12.0

In [74]:
np.median(a)

12.0