In [1]:
import numpy as np

### condition bases selection

In [2]:
salary = np.array([25000, 3500, 50000, 8500, 820000])

In [3]:
salary

array([ 25000,   3500,  50000,   8500, 820000])

In [4]:
salary[[0, 1, 3]]

array([25000,  3500,  8500])

In [5]:
salary[[True, True, False, True, False]]

array([25000,  3500,  8500])

### artihemtic operations on numpy array 

In [6]:
a = np.array([1,2,3,4,5,6])

In [7]:
a

array([1, 2, 3, 4, 5, 6])

In [8]:
a + 2

array([3, 4, 5, 6, 7, 8])

In [9]:
a * 2

array([ 2,  4,  6,  8, 10, 12])

In [10]:
a / 2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [11]:
salary

array([ 25000,   3500,  50000,   8500, 820000])

In [12]:
salary + 5000

array([ 30000,   8500,  55000,  13500, 825000])

In [13]:
salary % 2

array([0, 0, 0, 0, 0])

In [14]:
salary 

array([ 25000,   3500,  50000,   8500, 820000])

In [15]:
salary > 50000

array([False, False, False, False,  True])

In [16]:
salary > 30000

array([False, False,  True, False,  True])

In [18]:
salary[[False, False,  True, False,  True]]

array([ 50000, 820000])

In [20]:
salary[salary > 30000]

array([ 50000, 820000])

In [19]:
salary > 30000

array([False, False,  True, False,  True])

In [21]:
salary[salary < 50000]

array([25000,  3500,  8500])

In [24]:
salary[(salary > 5000) & (salary < 60000)]

array([25000, 50000,  8500])

In [22]:
salary > 5000

array([ True, False,  True,  True,  True])

In [23]:
salary < 60000

array([ True,  True,  True,  True, False])

In [25]:
salary[(salary > 60000) | (salary < 20000)]

array([  3500,   8500, 820000])

### create an array that has number from 5 to 100
### square all the values in the array
### take square root of all the values
### add 5000 to all the values in the array

### given array ages = [10, 35, 42, 85, 65, 62, 63, 52, 88, 92, 35]
### find total number of people whose age is greater than 80 
### find total number of people whose age is greater than 60 and less than 80
### find total number of people whose age is less than 20
### find total number of people whose is exactly 35
### find total number of people people whose age is even number 


In [26]:
a = np.arange(5, 101)

In [27]:
a

array([  5,   6,   7,   8,   9,  10,  11,  12,  13,  14,  15,  16,  17,
        18,  19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,
        31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,
        44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,
        57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
        70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,
        83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,
        96,  97,  98,  99, 100])

In [28]:
5 ** 2

25

In [29]:
a ** 2

array([   25,    36,    49,    64,    81,   100,   121,   144,   169,
         196,   225,   256,   289,   324,   361,   400,   441,   484,
         529,   576,   625,   676,   729,   784,   841,   900,   961,
        1024,  1089,  1156,  1225,  1296,  1369,  1444,  1521,  1600,
        1681,  1764,  1849,  1936,  2025,  2116,  2209,  2304,  2401,
        2500,  2601,  2704,  2809,  2916,  3025,  3136,  3249,  3364,
        3481,  3600,  3721,  3844,  3969,  4096,  4225,  4356,  4489,
        4624,  4761,  4900,  5041,  5184,  5329,  5476,  5625,  5776,
        5929,  6084,  6241,  6400,  6561,  6724,  6889,  7056,  7225,
        7396,  7569,  7744,  7921,  8100,  8281,  8464,  8649,  8836,
        9025,  9216,  9409,  9604,  9801, 10000])

In [30]:
a ** 0.5

array([ 2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
        3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
        4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949,
        5.        ,  5.09901951,  5.19615242,  5.29150262,  5.38516481,
        5.47722558,  5.56776436,  5.65685425,  5.74456265,  5.83095189,
        5.91607978,  6.        ,  6.08276253,  6.164414  ,  6.244998  ,
        6.32455532,  6.40312424,  6.4807407 ,  6.55743852,  6.63324958,
        6.70820393,  6.78232998,  6.8556546 ,  6.92820323,  7.        ,
        7.07106781,  7.14142843,  7.21110255,  7.28010989,  7.34846923,
        7.41619849,  7.48331477,  7.54983444,  7.61577311,  7.68114575,
        7.74596669,  7.81024968,  7.87400787,  7.93725393,  8.        ,
        8.06225775,  8.1240384 ,  8.18535277,  8.24621125,  8.30662386,
        8.36660027,  8.42614977,  8.48528137,  8.54400375,  8.60

In [31]:
25 ** 0.5

5.0

In [33]:
a = a + 5000

In [34]:
a

array([5005, 5006, 5007, 5008, 5009, 5010, 5011, 5012, 5013, 5014, 5015,
       5016, 5017, 5018, 5019, 5020, 5021, 5022, 5023, 5024, 5025, 5026,
       5027, 5028, 5029, 5030, 5031, 5032, 5033, 5034, 5035, 5036, 5037,
       5038, 5039, 5040, 5041, 5042, 5043, 5044, 5045, 5046, 5047, 5048,
       5049, 5050, 5051, 5052, 5053, 5054, 5055, 5056, 5057, 5058, 5059,
       5060, 5061, 5062, 5063, 5064, 5065, 5066, 5067, 5068, 5069, 5070,
       5071, 5072, 5073, 5074, 5075, 5076, 5077, 5078, 5079, 5080, 5081,
       5082, 5083, 5084, 5085, 5086, 5087, 5088, 5089, 5090, 5091, 5092,
       5093, 5094, 5095, 5096, 5097, 5098, 5099, 5100])

In [37]:
ages = np.array([10, 35, 42, 85, 65, 62, 63, 52, 88, 92, 35])

In [40]:
len(ages[ages > 80])

3

In [42]:
len(ages[(ages>60) & (ages<80)])

3

In [43]:
len(ages[ages<20])

1

In [44]:
len(ages[ages == 35])

2

In [47]:
a.sum()

485040

In [48]:
a.mean()

5052.5

In [49]:
a.std()

27.711309363988317

In [50]:
a.var()

767.9166666666666

In [53]:
ages>80

array([False, False, False,  True, False, False, False, False,  True,
        True, False])

In [54]:
True +True +True

3

In [57]:
len(ages[ages>80])

3

In [59]:
(ages>80).sum()

3

In [60]:
sum([1,2,3,])

6

In [61]:
np.array([1,2,3]).sum()

6

In [62]:
(ages>80).sum()

3

In [63]:
### manipulations of array