In [1]:
import numpy as np

In [2]:
def add_array(value, value2):
    return value + value2

In [3]:
def product_array(value, value2):
    return value * value2

In [4]:
array = np.array([1, 2, 3, 4, 5])
array

array([1, 2, 3, 4, 5])

In [5]:
array2 = np.array([6, 7, 8, 9, 10])
array2

array([ 6,  7,  8,  9, 10])

In [6]:
add_array(array, array2)

array([ 7,  9, 11, 13, 15])

In [7]:
product_array(array, array2)

array([ 6, 14, 24, 36, 50])

In [8]:
np.size(array)

5

In [9]:
np.ndim(array)

1

In [10]:
id(array)

1945740915504

In [11]:
array = array2.view()
array

array([ 6,  7,  8,  9, 10])

In [12]:
array2

array([ 6,  7,  8,  9, 10])

In [13]:
array[0] = 55

In [14]:
array

array([55,  7,  8,  9, 10])

In [15]:
array2

array([55,  7,  8,  9, 10])

In [16]:
array = array2.copy()

In [17]:
array

array([55,  7,  8,  9, 10])

In [18]:
array2

array([55,  7,  8,  9, 10])

In [19]:
array[0] = 100

In [20]:
array

array([100,   7,   8,   9,  10])

In [21]:
array2

array([55,  7,  8,  9, 10])

In [22]:
array.reshape(1, -1)

array([[100,   7,   8,   9,  10]])

In [23]:
np.arange(25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [24]:
a = np.arange(25)

In [25]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
a.resize((4, 4), refcheck=False)

In [27]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [28]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [29]:
a.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [30]:
a = np.arange(10)

In [31]:
b = a.ravel()

In [32]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
add_array(b, 5)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
def divide_array(value, value2):
    return value / value2

In [36]:
divide_array(b, 2)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [37]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
a[0] & b[0] == 0

True

In [40]:
a = np.arange(10)

In [41]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
b = np.arange(6, 20)

In [43]:
b

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [44]:
a[6]

6

In [45]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a[0]

0

In [47]:
a[1]

1

In [48]:
b

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [49]:
b[0]

6

In [50]:
a[7] & b[3] == 8

False

In [51]:
a[7] | b[2] == 8

False

In [52]:
b[2]

8

In [53]:
a[7] | b[2] == 8

False

In [54]:
a[7] 

7

In [55]:
b[1]

7

In [56]:
a[7] & b[1] == 1

False

In [57]:
a[7] & b[1] == 7

True

In [58]:
a[7] | b[2] == 7

False

In [59]:
bol_true = np.array([True, False])

In [60]:
bol_true

array([ True, False])

In [61]:
bol_false = np.array([False, False])

In [62]:
bol_false

array([False, False])

In [63]:
bol_true & bol_false

array([False, False])

In [64]:
bol_true | bol_false

array([ True, False])

In [65]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
b

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [67]:
a[7]

7

In [68]:
b[1]

7

In [69]:
a[7] & b[1] == 7

True

In [70]:
a[8] | b[1] == 8

False

In [71]:
a[8]

8

In [72]:
True | True

True

In [73]:
True | False

True

In [74]:
False | True

True

In [75]:
False | False

False

In [76]:
arr = np.array([1, 2, 3, 4], ndmin=2)

In [77]:
arr

array([[1, 2, 3, 4]])

In [78]:
True | False

True

In [79]:
a = np.array([0, 1, 2, 3, 4, 5])
b = np.array([4, 5, 6, 7, 8, 9])

In [80]:
a[4]

4

In [81]:
b[0]

4

In [82]:
a[4] & b[1]

4

In [87]:
a[4] | b[1] == 4

False