In [1]:
import numpy as np

In [2]:
test_array = np.array([1,2,3])

In [3]:
test_array

array([1, 2, 3])

In [4]:
salary = np.array([[25000, 3500], [50000, 8500], [820000, 50000]])

In [5]:
salary

array([[ 25000,   3500],
       [ 50000,   8500],
       [820000,  50000]])

In [6]:
salary[[0, 1]]

array([[25000,  3500],
       [50000,  8500]])

In [7]:
salary[[True]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 3 but corresponding boolean dimension is 1

In [36]:
salary > 10000

array([[ True, False],
       [ True, False],
       [ True,  True]])

In [8]:
salary[[True, False], [True, False], [True, True]]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [9]:
salary[salary < 50000]

array([25000,  3500,  8500])

In [10]:
salary[(salary > 5000) & (salary < 60000)]

array([25000, 50000,  8500, 50000])

In [11]:
salary

array([[ 25000,   3500],
       [ 50000,   8500],
       [820000,  50000]])

In [12]:
new_salary = salary + 5000

In [13]:
new_salary

array([[ 30000,   8500],
       [ 55000,  13500],
       [825000,  55000]])

In [14]:
new_salary > 50000

array([[False, False],
       [ True, False],
       [ True,  True]])

In [15]:
new_salary[new_salary > 50000]

array([ 55000, 825000,  55000])

In [16]:
student_score = np.array([75, 80, 60, 65, 95, 88, 96])

In [17]:
student_score

array([75, 80, 60, 65, 95, 88, 96])

In [18]:
len(student_score[student_score >= 80])

4

In [19]:
(student_score >= 80).sum()

4

In [20]:
(student_score <= 80).sum()

4

In [21]:
np.mean(student_score)


79.85714285714286

In [22]:
np.sum(student_score)

559

In [23]:
student_score

array([75, 80, 60, 65, 95, 88, 96])

In [24]:
student_score[student_score % 2 == 0]

array([80, 60, 88, 96])

In [25]:
(student_score % 2 == 0).sum()

4

In [26]:
np.mean(student_score)

79.85714285714286

In [27]:
np.std(student_score)

13.06498670305563

In [28]:
np.var(student_score)

170.69387755102042

In [29]:
student_score[True]

array([[75, 80, 60, 65, 95, 88, 96]])

In [31]:
student_score[[True, False, True, True, False, True, True]]

array([75, 60, 65, 88, 96])

In [33]:
new_salary[0, 1]

8500

In [34]:
new_salary

array([[ 30000,   8500],
       [ 55000,  13500],
       [825000,  55000]])

In [35]:
new_salary[1, 0]

55000

In [38]:
new_salary

array([[ 30000,   8500],
       [ 55000,  13500],
       [825000,  55000]])

In [39]:
new_salary + (0.2 * new_salary)

array([[ 36000.,  10200.],
       [ 66000.,  16200.],
       [990000.,  66000.]])

In [40]:
new_salary.sum()

987000

In [41]:
np.sum(new_salary)

987000