In [1]:
import numpy as np
import pandas as pd


In [2]:
df = pd.read_csv("collegePlace.csv")


In [3]:
df.head(4)

Age  Gender                         Stream  Internships  CGPA  Hostel  \
0   22    Male  Electronics And Communication            1     8       1   
1   21  Female               Computer Science            0     7       1   
2   22  Female         Information Technology            1     6       0   
3   21    Male         Information Technology            0     8       0   

   HistoryOfBacklogs  PlacedOrNot  
0                  1            1  
1                  1            1  
2                  0            1  
3                  1            1

In [4]:
df.drop(["Age","Gender","Stream","Hostel"],axis=1,inplace=True)


In [60]:
df

Internships  CGPA  HistoryOfBacklogs  PlacedOrNot
0               1     8                  1            1
1               0     7                  1            1
2               1     6                  0            1
3               0     8                  1            1
4               0     8                  0            1
...           ...   ...                ...          ...
2961            0     7                  0            0
2962            1     7                  0            0
2963            1     7                  0            0
2964            1     7                  0            0
2965            0     8                  0            1

[2966 rows x 4 columns]

In [7]:
df.isnull().sum()


Internships          0
CGPA                 0
HistoryOfBacklogs    0
PlacedOrNot          0
dtype: int64

In [8]:
df.Internships.unique()

array([1, 0, 2, 3])

In [9]:
df.CGPA.unique()

array([8, 7, 6, 9, 5])

In [10]:
df.HistoryOfBacklogs.unique()

array([1, 0])

In [11]:
df.PlacedOrNot.unique()

array([1, 0])

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scalar = StandardScaler()

In [50]:
scalar.fit(df)

StandardScaler()

In [53]:
x=scalar.transform(df)

In [58]:
d= pd.DataFrame(x,columns =df.columns)

In [61]:
d

Internships      CGPA  HistoryOfBacklogs  PlacedOrNot
0        0.400445  0.957191           2.050246     0.899800
1       -0.950773 -0.076310           2.050246     0.899800
2        0.400445 -1.109812          -0.487746     0.899800
3       -0.950773  0.957191           2.050246     0.899800
4       -0.950773  0.957191          -0.487746     0.899800
...           ...       ...                ...          ...
2961    -0.950773 -0.076310          -0.487746    -1.111358
2962     0.400445 -0.076310          -0.487746    -1.111358
2963     0.400445 -0.076310          -0.487746    -1.111358
2964     0.400445 -0.076310          -0.487746    -1.111358
2965    -0.950773  0.957191          -0.487746     0.899800

[2966 rows x 4 columns]

In [84]:
from sklearn.model_selection import train_test_split

In [85]:
X_train, X_test, y_train, y_test = train_test_split(d[["Internships","CGPA","HistoryOfBacklogs"]],d.PlacedOrNot, test_size=0.20, random_state=42)

In [86]:
X_train

Internships      CGPA  HistoryOfBacklogs
2458     0.400445  0.957191          -0.487746
509     -0.950773 -0.076310          -0.487746
1370    -0.950773 -0.076310           2.050246
1352     0.400445 -0.076310          -0.487746
1779     0.400445  0.957191          -0.487746
...           ...       ...                ...
1638     3.102883  0.957191          -0.487746
1095     0.400445 -1.109812          -0.487746
1130     0.400445  0.957191          -0.487746
1294    -0.950773 -0.076310          -0.487746
860      0.400445 -0.076310          -0.487746

[2372 rows x 3 columns]

In [87]:
y_train

2458    0.899800
509    -1.111358
1370   -1.111358
1352    0.899800
1779    0.899800
          ...   
1638    0.899800
1095   -1.111358
1130    0.899800
1294   -1.111358
860    -1.111358
Name: PlacedOrNot, Length: 2372, dtype: float64

In [88]:

from sklearn.linear_model import LinearRegression

In [89]:
model =LinearRegression()

In [90]:
model.fit(X_train,y_train)

LinearRegression()

In [91]:
X_test

Internships      CGPA  HistoryOfBacklogs
2395    -0.950773 -0.076310           2.050246
794      1.751664  0.957191           2.050246
1894     0.400445  0.957191          -0.487746
332     -0.950773 -0.076310          -0.487746
2023     0.400445 -0.076310           2.050246
...           ...       ...                ...
1938     0.400445  0.957191           2.050246
2607    -0.950773  0.957191          -0.487746
1395    -0.950773 -0.076310           2.050246
602      1.751664 -0.076310          -0.487746
2308     0.400445 -0.076310           2.050246

[594 rows x 3 columns]

In [92]:
y_test

2395   -1.111358
794     0.899800
1894    0.899800
332    -1.111358
2023   -1.111358
          ...   
1938    0.899800
2607    0.899800
1395   -1.111358
602     0.899800
2308    0.899800
Name: PlacedOrNot, Length: 594, dtype: float64

In [93]:
p =model.predict(X_test)

In [103]:
z=pd.DataFrame(p)

In [81]:
z

0
0    0.440898
1    0.968698
2    0.873694
3    0.456022
4    0.551026
..        ...
589  0.858570
590  0.763566
591  0.440898
592  0.676278
593  0.551026

[594 rows x 1 columns]

In [104]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [106]:
mean_absolute_error(y_test, p)

0.6894507144343114

In [107]:
mean_squared_error(y_test, p)

0.6761562478393073

In [108]:
r2_score(y_test, p)

0.32912770226347576