In [20]:
import numpy as np

In [21]:
a = np.arange(6)

In [22]:
a

array([0, 1, 2, 3, 4, 5])

In [23]:
np.sum(a)/np.size(a)

2.5

In [24]:
array_2d = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])

In [25]:
array_2d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [26]:
np.shape(array_2d)

(5, 2)

In [27]:
np.size(array_2d)

10

In [28]:
np.ndim(array_2d)

2

In [33]:
np.itemsize(array_2d)

AttributeError: module 'numpy' has no attribute 'itemsize'

In [ ]:
array_2d

In [ ]:
array_2d[::2]

In [ ]:
array_2d[1, 1]

In [ ]:
array_multiply = array_2d * 2

In [ ]:
array_multiply

In [31]:
array_add = array_2d + 2
array_add

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [32]:
array_add

array([[ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [13]:
array_2d

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [34]:
add_array = array_add + array_2d
add_array

array([[ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22]])

In [35]:
np.max(add_array)

22

In [36]:
np.min(add_array)

4

In [37]:
np.size(add_array)

10

In [38]:
mean = np.sum(add_array)/np.mean(add_array)
f'Mean: {mean}'

'Mean: 10.0'

In [39]:
mix_array = np.array([4, 6, 8])

In [40]:
mix_array

array([4, 6, 8])

In [42]:
np.dtype(mix_array)

TypeError: Cannot construct a dtype from an array

In [43]:
even_number = np.arange(0, 10, 2)

In [44]:
even_number

array([0, 2, 4, 6, 8])

In [45]:
zero_array = np.zeros((3, 4), dtype='int')
zero_array

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [46]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
a * b

array([ 4, 10, 18])

In [47]:
random_array = np.random.randint(1, 100, 7)
sqrt_array = np.sqrt(random_array)

In [48]:
random_array

array([65, 16, 76, 65, 96, 62, 40])

In [49]:
sqrt_array

array([8.06225775, 4.        , 8.71779789, 8.06225775, 9.79795897,
       7.87400787, 6.32455532])

In [50]:
arr = np.array([10, 20, 30, 40, 50])

In [51]:
arr[1:4]

array([20, 30, 40])

In [52]:
array1 = np.random.randint(1, 50, (4, 5))
array1

array([[20, 46, 37,  3, 19],
       [ 5, 26, 39, 32,  5],
       [25, 33, 38, 23, 31],
       [13, 31, 33, 35, 34]])

In [53]:
array1[:, 1]

array([46, 26, 33, 31])

In [54]:
element_8 = np.random.randint(1, 20, 8)
ele_8_array = np.array([element_8])
ele_8_array

array([[ 8,  7, 14,  6,  5, 15, 12,  1]])

In [55]:
f'Sum: {np.sum(ele_8_array)}'

'Sum: 68'

In [56]:
f'Average: {np.mean(ele_8_array)}'

'Average: 8.5'